# Generated by Django 3.1.4 on 2021-07-01 00:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='stage',
        ),
        migrations.AddField(
            model_name='history',
            name='stages',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
