# Generated by Django 3.1.4 on 2021-07-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210701_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='unread_notification',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
