# Generated by Django 2.2.7 on 2021-07-28 04:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210703_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_payment',
            name='pricing_options',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
