# Generated by Django 2.2.7 on 2021-07-28 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_pricing_payment_pricing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_collection', to='App.Collection'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='license',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_pricing', to='App.FormationPricing'),
        ),
    ]
