# Generated by Django 2.2.7 on 2021-07-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210728_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_account_nb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
