# Generated by Django 2.2.7 on 2021-07-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_company_max_account_nb'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='for_landing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
