# Generated by Django 2.2.7 on 2021-07-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_company_for_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_payment',
            name='subscription_period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
